### ISSUE TITLE
(Suggestion) RSS feed viewer!

### ISSUE THREAD

**Issue by WyattHBrown** [merlinfuchs/blimp#1]
I absolutely love this thing! have it running on my server display since it really adds an element of information that I was looking for! I definitely want to see where this thing goes in the future! I would suggest looking into the possibility to add another info display for RSS feeds. It would be quite an interesting component to have. With it being a side monitor, RSS feeds can carry a lot of information on their own, and I think it would work great with this!

**Comment by merlinfuchs** [comment]
Really happy you like the project and thanks for the suggestion!

What do you think would be the best way to display the items from the RSS feed? Maybe just a list with the title and description of each iteam 🤔 Maybe you ever a better idea!
