### ISSUE TITLE
Issue with Panic Error on First Run After Installation

### ISSUE THREAD

**Issue by eugconrad** [merlinfuchs/blimp#4]
I encountered an issue while trying to run the blimp application after installing it on my system. Here are the details:

Go Version: go1.21.0 linux/arm64
System Version: Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux
Issue:

Upon running the blimp application using the command blimp, I encountered a panic error with the following stack trace:
Issue:
```console
pi@raspberrypi:~$ blimp
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/merlinfuchs/blimp/internal/widgets/weather.(*StatusView).updateView(0x40000cede0)
        /home/pi/go/pkg/mod/github.com/merlinfuchs/blimp@v0.2.0/internal/widgets/weather/weather.go:92 +0x22a0
github.com/merlinfuchs/blimp/internal/widgets/weather.(*StatusView).updateData(0x40000cede0)
        /home/pi/go/pkg/mod/github.com/merlinfuchs/blimp@v0.2.0/internal/widgets/weather/weather.go:75 +0x190
github.com/merlinfuchs/blimp/internal/widgets/weather.(*StatusView).Start(0x40000cede0)
        /home/pi/go/pkg/mod/github.com/merlinfuchs/blimp@v0.2.0/internal/widgets/weather/weather.go:44 +0x20
github.com/merlinfuchs/blimp/internal.constructPages({0x40000945f0, 0x2, 0x44f9bb?}, 0x40001a5890)
        /home/pi/go/pkg/mod/github.com/merlinfuchs/blimp@v0.2.0/internal/app.go:149 +0x55c
github.com/merlinfuchs/blimp/internal.AppEntry()
        /home/pi/go/pkg/mod/github.com/merlinfuchs/blimp@v0.2.0/internal/app.go:35 +0x29c
main.main()
        /home/pi/go/pkg/mod/github.com/merlinfuchs/blimp@v0.2.0/main.go:28 +0xe4
```

Upon running the blimp application using the command blimp, I encountered a panic error with the following stack trace:
It appears that the application is encountering an "index out of range" error during its execution.

Steps to Reproduce:
Install blimp using the command: go install github.com/merlinfuchs/blimp@latest
Run the blimp application: blimp

**Comment by merlinfuchs** [comment]
Hi, thanks for reporting the issue! These error messages definitely deserves some imrovements 😅 

I believe this is because you haven't set the api key for openweathermap.org. You can get a free api key here: https://openweathermap.org/price

See the readme on how to set the api key in the config file: https://github.com/merlinfuchs/blimp#configure-the-widgets If you don't want to use the weather widgets you can also remove it from the layout so you don't need to set the api key.

**Comment by eugconrad** [comment]
Certainly, I didn't specify the token from openweathermap.org. After digging into the source code a bit, I realized that the error indeed stems from the weather widget, as the openweathermap.org token is missing.

I didn't have prior experience with Go, which is why I couldn't figure out where the `blimp.toml` file should be located. In which directory should I look for it?

It would be helpful to add more details to the README regarding my case, such as the path to the `blimp.toml` file and the necessity of adding an openweathermap.org token for the initial setup. It seems that the default configuration also includes the weather widget, which would naturally require an openweathermap.org token.

Apologies if I appeared confused or silly! :D

**Comment by merlinfuchs** [comment]
Blimp is looking for the `blimp.toml` config file in the directory where you run it (working directory). So if you run it from `/home/x/` you should create the `blimp.toml` file at `/home/x/blimp.toml`.

The only value that you have to set in the config file is your openweathermap.org api key:
```toml
[widgets.weather]
owm_api_key = "your-key"
```

All the other config values are optional and can be found in the README :)

**Comment by eugconrad** [comment]
Oh my, why didn't I think of the working directory right away... I was searching for that file everywhere. I suspected the working directory to be the directory where the program is installed... :D

Anyway, creating the `blimp.toml` file in the home directory and running `blimp` from there solved my problem. Thanks!
